### ISSUE TITLE
directory configuration is non-traditional in the `compile` goal

### ISSUE THREAD

**Issue by yegor256** [objectionary/opeo-maven-plugin#103]
At the moment, the configuration of input and output directories is done in a weird non-Maven way. I suggest to have two arguments for the `compile` goal: 

  * `sourcesDir` defaults to `${project.build.directory}/generated-sources/xmir2`
  * `outputDir` defaults to `${project.build.directory}/generated-sources/xmir`

No other parameters to specify the locations.

Don't forget to set properties, like it's done here: https://github.com/objectionary/eo/blob/master/eo-maven-plugin/src/main/java/org/eolang/maven/AssembleMojo.java#L74 Should be `opeo.sourcesDir` and `opeo.outputDir`

**Comment by yegor256** [comment]
@volodya-lombrozo can you please release this one?

**Comment by volodya-lombrozo** [comment]
@yegor256 this feature is already released in the '0.1.2' version.

**Comment by volodya-lombrozo** [comment]
https://github.com/objectionary/opeo-maven-plugin/pull/106#issuecomment-1900501620
