### ISSUE TITLE
directory configuration is non-traditional in the `decompile` goal

### ISSUE THREAD

**Issue by yegor256** [objectionary/opeo-maven-plugin#104]
At the moment, the configuration of input and output directories is done in a weird non-Maven way. I suggest to have two arguments for the `decompile` goal: 

  * `sourcesDir` defaults to `${project.build.directory}/generated-sources/xmir`
  * `outputDir` defaults to `${project.build.directory}/generated-sources/xmir2`

No other parameters to specify the locations.

Don't forget to set properties, like it's done here: https://github.com/objectionary/eo/blob/master/eo-maven-plugin/src/main/java/org/eolang/maven/AssembleMojo.java#L74 Should be `opeo.sourcesDir` and `opeo.outputDir`

**Comment by yegor256** [comment]
@volodya-lombrozo can you please release this one?

**Comment by volodya-lombrozo** [comment]
@yegor256 this feature should be already released in the '0.1.2' version.

**Comment by yegor256** [comment]
@volodya-lombrozo didn't find it [here](https://github.com/objectionary/opeo-maven-plugin/releases), that's why asking

**Comment by volodya-lombrozo** [comment]
@yegor256 It is a well-known problem. I've created an [issue](https://github.com/yegor256/rultor/issues/1840#issue-2092460981) to emphasise it and published one more duplicated version `0.1.3` which you can find in release section.
