### ISSUE TITLE
wrong signature in the method generated

### ISSUE THREAD

**Issue by yegor256** [objectionary/opeo-maven-plugin#110]
See https://github.com/objectionary/jeo-maven-plugin/issues/432

It seems that opeo generates wrong bytecode for this particular case.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#116](https://github.com/objectionary/opeo-maven-plugin/issues/116), [#117](https://github.com/objectionary/opeo-maven-plugin/issues/117) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#117](https://github.com/objectionary/opeo-maven-plugin/issues/117) is still not solved; solved: [#116](https://github.com/objectionary/opeo-maven-plugin/issues/116).

**Comment by volodya-lombrozo** [comment]
@yegor256 Did we solve this issue?

**Comment by yegor256** [comment]
@volodya-lombrozo yes, thanks!

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#117](https://github.com/objectionary/opeo-maven-plugin/issues/117), [#156](https://github.com/objectionary/opeo-maven-plugin/issues/156) are still not solved; solved: [#116](https://github.com/objectionary/opeo-maven-plugin/issues/116).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#117](https://github.com/objectionary/opeo-maven-plugin/issues/117), [#158](https://github.com/objectionary/opeo-maven-plugin/issues/158) are still not solved; solved: [#116](https://github.com/objectionary/opeo-maven-plugin/issues/116), [#156](https://github.com/objectionary/opeo-maven-plugin/issues/156).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#117](https://github.com/objectionary/opeo-maven-plugin/issues/117) is still not solved; solved: [#116](https://github.com/objectionary/opeo-maven-plugin/issues/116), [#156](https://github.com/objectionary/opeo-maven-plugin/issues/156), [#158](https://github.com/objectionary/opeo-maven-plugin/issues/158).

**Comment by 0pdd** [comment]
@yegor256 all 4 puzzles are solved here: [#116](https://github.com/objectionary/opeo-maven-plugin/issues/116), [#117](https://github.com/objectionary/opeo-maven-plugin/issues/117), [#156](https://github.com/objectionary/opeo-maven-plugin/issues/156), [#158](https://github.com/objectionary/opeo-maven-plugin/issues/158).
