### ISSUE TITLE
Large test with Spring Boot, Http and Factorial

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#200]
In order to make the `opeo-maven-plugin` useful in production, we should incorporate a large integration test that will mimic a "realistic" scenario. We have already done something similar for the `jeo-maven-plugin`, and you can find this test right  [here](https://github.com/objectionary/jeo-maven-plugin/tree/master/src/it/spring-fat). Moreover, we have a [plan](https://github.com/objectionary/jeo-maven-plugin/issues/548) to enhance this test to utilize HTTP.

Therefore, we have to create a similar test for the `opeo-maven-plugin` which will contain a Spring Boot Application with an HTTP server and a bean that will calculate [Fibonacci](https://github.com/objectionary/benchmark/pull/40/files) numbers.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219), [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220), [#228](https://github.com/objectionary/opeo-maven-plugin/issues/228), [#229](https://github.com/objectionary/opeo-maven-plugin/issues/229) are still not solved; solved: [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220), [#229](https://github.com/objectionary/opeo-maven-plugin/issues/229), [#242](https://github.com/objectionary/opeo-maven-plugin/issues/242) are still not solved; solved: [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219), [#228](https://github.com/objectionary/opeo-maven-plugin/issues/228).

**Comment by 0pdd** [comment]
@volodya-lombrozo 4 puzzles [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220), [#229](https://github.com/objectionary/opeo-maven-plugin/issues/229), [#242](https://github.com/objectionary/opeo-maven-plugin/issues/242), [#249](https://github.com/objectionary/opeo-maven-plugin/issues/249) are still not solved; solved: [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219), [#228](https://github.com/objectionary/opeo-maven-plugin/issues/228).

**Comment by 0pdd** [comment]
@volodya-lombrozo 5 puzzles [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220), [#229](https://github.com/objectionary/opeo-maven-plugin/issues/229), [#242](https://github.com/objectionary/opeo-maven-plugin/issues/242), [#249](https://github.com/objectionary/opeo-maven-plugin/issues/249), [#260](https://github.com/objectionary/opeo-maven-plugin/issues/260) are still not solved; solved: [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219), [#228](https://github.com/objectionary/opeo-maven-plugin/issues/228).

**Comment by 0pdd** [comment]
@volodya-lombrozo 15 puzzles [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220), [#229](https://github.com/objectionary/opeo-maven-plugin/issues/229), [#242](https://github.com/objectionary/opeo-maven-plugin/issues/242), [#249](https://github.com/objectionary/opeo-maven-plugin/issues/249), [#260](https://github.com/objectionary/opeo-maven-plugin/issues/260), [#274](https://github.com/objectionary/opeo-maven-plugin/issues/274), [#275](https://github.com/objectionary/opeo-maven-plugin/issues/275), [#276](https://github.com/objectionary/opeo-maven-plugin/issues/276), [#277](https://github.com/objectionary/opeo-maven-plugin/issues/277), [#278](https://github.com/objectionary/opeo-maven-plugin/issues/278), [#279](https://github.com/objectionary/opeo-maven-plugin/issues/279), [#280](https://github.com/objectionary/opeo-maven-plugin/issues/280), [#281](https://github.com/objectionary/opeo-maven-plugin/issues/281), [#282](https://github.com/objectionary/opeo-maven-plugin/issues/282), [#283](https://github.com/objectionary/opeo-maven-plugin/issues/283) are still not solved; solved: [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219), [#228](https://github.com/objectionary/opeo-maven-plugin/issues/228).

**Comment by 0pdd** [comment]
@volodya-lombrozo 15 puzzles [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220), [#229](https://github.com/objectionary/opeo-maven-plugin/issues/229), [#242](https://github.com/objectionary/opeo-maven-plugin/issues/242), [#249](https://github.com/objectionary/opeo-maven-plugin/issues/249), [#260](https://github.com/objectionary/opeo-maven-plugin/issues/260), [#274](https://github.com/objectionary/opeo-maven-plugin/issues/274), [#275](https://github.com/objectionary/opeo-maven-plugin/issues/275), [#276](https://github.com/objectionary/opeo-maven-plugin/issues/276), [#277](https://github.com/objectionary/opeo-maven-plugin/issues/277), [#278](https://github.com/objectionary/opeo-maven-plugin/issues/278), [#279](https://github.com/objectionary/opeo-maven-plugin/issues/279), [#280](https://github.com/objectionary/opeo-maven-plugin/issues/280), [#281](https://github.com/objectionary/opeo-maven-plugin/issues/281), [#283](https://github.com/objectionary/opeo-maven-plugin/issues/283), [#286](https://github.com/objectionary/opeo-maven-plugin/issues/286) are still not solved; solved: [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219), [#228](https://github.com/objectionary/opeo-maven-plugin/issues/228), [#282](https://github.com/objectionary/opeo-maven-plugin/issues/282).

**Comment by 0pdd** [comment]
@volodya-lombrozo 14 puzzles [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220), [#229](https://github.com/objectionary/opeo-maven-plugin/issues/229), [#242](https://github.com/objectionary/opeo-maven-plugin/issues/242), [#249](https://github.com/objectionary/opeo-maven-plugin/issues/249), [#260](https://github.com/objectionary/opeo-maven-plugin/issues/260), [#274](https://github.com/objectionary/opeo-maven-plugin/issues/274), [#275](https://github.com/objectionary/opeo-maven-plugin/issues/275), [#276](https://github.com/objectionary/opeo-maven-plugin/issues/276), [#277](https://github.com/objectionary/opeo-maven-plugin/issues/277), [#278](https://github.com/objectionary/opeo-maven-plugin/issues/278), [#279](https://github.com/objectionary/opeo-maven-plugin/issues/279), [#280](https://github.com/objectionary/opeo-maven-plugin/issues/280), [#281](https://github.com/objectionary/opeo-maven-plugin/issues/281), [#286](https://github.com/objectionary/opeo-maven-plugin/issues/286) are still not solved; solved: [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219), [#228](https://github.com/objectionary/opeo-maven-plugin/issues/228), [#282](https://github.com/objectionary/opeo-maven-plugin/issues/282), [#283](https://github.com/objectionary/opeo-maven-plugin/issues/283).

**Comment by volodya-lombrozo** [comment]
We implemented this test [here](https://github.com/objectionary/opeo-maven-plugin/tree/master/src/it/spring-fat).

**Comment by 0pdd** [comment]
@volodya-lombrozo 13 puzzles [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220), [#242](https://github.com/objectionary/opeo-maven-plugin/issues/242), [#249](https://github.com/objectionary/opeo-maven-plugin/issues/249), [#260](https://github.com/objectionary/opeo-maven-plugin/issues/260), [#274](https://github.com/objectionary/opeo-maven-plugin/issues/274), [#275](https://github.com/objectionary/opeo-maven-plugin/issues/275), [#276](https://github.com/objectionary/opeo-maven-plugin/issues/276), [#277](https://github.com/objectionary/opeo-maven-plugin/issues/277), [#278](https://github.com/objectionary/opeo-maven-plugin/issues/278), [#279](https://github.com/objectionary/opeo-maven-plugin/issues/279), [#280](https://github.com/objectionary/opeo-maven-plugin/issues/280), [#281](https://github.com/objectionary/opeo-maven-plugin/issues/281), [#286](https://github.com/objectionary/opeo-maven-plugin/issues/286) are still not solved; solved: [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219), [#228](https://github.com/objectionary/opeo-maven-plugin/issues/228), [#229](https://github.com/objectionary/opeo-maven-plugin/issues/229), [#282](https://github.com/objectionary/opeo-maven-plugin/issues/282), [#283](https://github.com/objectionary/opeo-maven-plugin/issues/283).

**Comment by 0pdd** [comment]
@volodya-lombrozo 13 puzzles [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220), [#242](https://github.com/objectionary/opeo-maven-plugin/issues/242), [#249](https://github.com/objectionary/opeo-maven-plugin/issues/249), [#274](https://github.com/objectionary/opeo-maven-plugin/issues/274), [#275](https://github.com/objectionary/opeo-maven-plugin/issues/275), [#276](https://github.com/objectionary/opeo-maven-plugin/issues/276), [#277](https://github.com/objectionary/opeo-maven-plugin/issues/277), [#278](https://github.com/objectionary/opeo-maven-plugin/issues/278), [#279](https://github.com/objectionary/opeo-maven-plugin/issues/279), [#280](https://github.com/objectionary/opeo-maven-plugin/issues/280), [#281](https://github.com/objectionary/opeo-maven-plugin/issues/281), [#286](https://github.com/objectionary/opeo-maven-plugin/issues/286), [#382](https://github.com/objectionary/opeo-maven-plugin/issues/382) are still not solved; solved: [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219), [#228](https://github.com/objectionary/opeo-maven-plugin/issues/228), [#229](https://github.com/objectionary/opeo-maven-plugin/issues/229), [#260](https://github.com/objectionary/opeo-maven-plugin/issues/260), [#282](https://github.com/objectionary/opeo-maven-plugin/issues/282), [#283](https://github.com/objectionary/opeo-maven-plugin/issues/283).

**Comment by 0pdd** [comment]
@volodya-lombrozo 14 puzzles [#220](https://github.com/objectionary/opeo-maven-plugin/issues/220), [#242](https://github.com/objectionary/opeo-maven-plugin/issues/242), [#249](https://github.com/objectionary/opeo-maven-plugin/issues/249), [#274](https://github.com/objectionary/opeo-maven-plugin/issues/274), [#275](https://github.com/objectionary/opeo-maven-plugin/issues/275), [#276](https://github.com/objectionary/opeo-maven-plugin/issues/276), [#278](https://github.com/objectionary/opeo-maven-plugin/issues/278), [#279](https://github.com/objectionary/opeo-maven-plugin/issues/279), [#280](https://github.com/objectionary/opeo-maven-plugin/issues/280), [#281](https://github.com/objectionary/opeo-maven-plugin/issues/281), [#286](https://github.com/objectionary/opeo-maven-plugin/issues/286), [#382](https://github.com/objectionary/opeo-maven-plugin/issues/382), [#387](https://github.com/objectionary/opeo-maven-plugin/issues/387), [#388](https://github.com/objectionary/opeo-maven-plugin/issues/388) are still not solved; solved: [#219](https://github.com/objectionary/opeo-maven-plugin/issues/219), [#228](https://github.com/objectionary/opeo-maven-plugin/issues/228), [#229](https://github.com/objectionary/opeo-maven-plugin/issues/229), [#260](https://github.com/objectionary/opeo-maven-plugin/issues/260), [#277](https://github.com/objectionary/opeo-maven-plugin/issues/277), [#282](https://github.com/objectionary/opeo-maven-plugin/issues/282), [#283](https://github.com/objectionary/opeo-maven-plugin/issues/283).
