### ISSUE TITLE
No PHI expressions generated for the "Full Spring Fat Jar Integration Test"

### ISSUE THREAD

**Issue by deemp** [objectionary/opeo-maven-plugin#272]
@volodya-lombrozo, I followed the instructions on generating PHI expressions for the "Full Spring Fat Jar Integration Test" ([link](https://github.com/objectionary/opeo-maven-plugin/tree/master/src/it/spring-fat#phi-expressions)) and got no output in `target/generated-sources/phi-expressions`.

**Comment by volodya-lombrozo** [comment]
@deemp I've made a mistake in the documentation. 
Could you check the following folder, please:

```
target/it/spring-fat/target/generated-sources/phi-expressions
```
instead of `target/generated-sources/phi-expressions`. It should contain what you are looking for.

**Comment by deemp** [comment]
@volodya-lombrozo, thank you! That directory indeed contains `.phi` files.
