### ISSUE TITLE
Decompile and Print PHI for Factorial

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#284]
We need to decompile and and convert to PHI expression `Factorial` class in the `spring-fat` integration test. Currently we don't decompile it because we haven't implemented `IF_ICMPGT` instruction yet.

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#287](https://github.com/objectionary/opeo-maven-plugin/issues/287), [#288](https://github.com/objectionary/opeo-maven-plugin/issues/288), [#289](https://github.com/objectionary/opeo-maven-plugin/issues/289) are still not solved.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.2.0`, title is `Version 0.2.0`.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.2.0`, title is `Version 0.2.0`.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.2.1`, title is `Version 0.2.1`.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.2.3`, title is `Version 0.2.3`.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.2.3`, title is `0.2.3`.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.2.4`, title is `0.2.4`.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.2.0`, title is `Version 0.2.0`.

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#287](https://github.com/objectionary/opeo-maven-plugin/issues/287), [#289](https://github.com/objectionary/opeo-maven-plugin/issues/289), [#391](https://github.com/objectionary/opeo-maven-plugin/issues/391) are still not solved; solved: [#288](https://github.com/objectionary/opeo-maven-plugin/issues/288).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#287](https://github.com/objectionary/opeo-maven-plugin/issues/287), [#289](https://github.com/objectionary/opeo-maven-plugin/issues/289) are still not solved; solved: [#288](https://github.com/objectionary/opeo-maven-plugin/issues/288), [#391](https://github.com/objectionary/opeo-maven-plugin/issues/391).
