### ISSUE TITLE
Does 'opeo-maven-plugin' have any plans to support Java 8?

### ISSUE THREAD

**Issue by guangwang126** [objectionary/opeo-maven-plugin#290]
Does 'opeo-maven-plugin' have any plans to support Java 8?

**Comment by volodya-lombrozo** [comment]
@guangwang126  I'll put it in the plan.

**Comment by 0pdd** [comment]
@guangwang126 the puzzle [#305](https://github.com/objectionary/opeo-maven-plugin/issues/305) is still not solved.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.2.2`, title is `Version 0.2.2`.

**Comment by 0pdd** [comment]
@guangwang126 the only puzzle [#305](https://github.com/objectionary/opeo-maven-plugin/issues/305) is solved here.
