### ISSUE TITLE
Don't use 'scope' attribute

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#316]
Currently we use `scope` attribute as a crutch to hide the problem with additional meta-information like:
- descriptors
- types
- return values
- method types 
- and so on

We need to replace the usage of `scope` attribute with some object.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#323](https://github.com/objectionary/opeo-maven-plugin/issues/323) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#323](https://github.com/objectionary/opeo-maven-plugin/issues/323), [#327](https://github.com/objectionary/opeo-maven-plugin/issues/327), [#328](https://github.com/objectionary/opeo-maven-plugin/issues/328) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#323](https://github.com/objectionary/opeo-maven-plugin/issues/323), [#328](https://github.com/objectionary/opeo-maven-plugin/issues/328) are still not solved; solved: [#327](https://github.com/objectionary/opeo-maven-plugin/issues/327).
