### ISSUE TITLE
Constructor.java:42-45: Continue enable 'spring-fat'...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/opeo-maven-plugin#344]
The puzzle `329-93a273ea` from #329 has to be resolved: 

https://github.com/objectionary/opeo-maven-plugin/blob/c2af3985f231c712e8b53ede8b6e102a3747c6d4/src/main/java/org/eolang/opeo/ast/Constructor.java#L42-L45

The puzzle was created by @volodya-lombrozo on 12-Jul-24. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#361](https://github.com/objectionary/opeo-maven-plugin/issues/361) is still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#361](https://github.com/objectionary/opeo-maven-plugin/issues/361), [#363](https://github.com/objectionary/opeo-maven-plugin/issues/363) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#361](https://github.com/objectionary/opeo-maven-plugin/issues/361), [#363](https://github.com/objectionary/opeo-maven-plugin/issues/363), [#366](https://github.com/objectionary/opeo-maven-plugin/issues/366) are still not solved.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.3.1`, title is `Version 0.3.1`.
