### ISSUE TITLE
SameXml.java:84-86: Avoid Using Public Static Method From...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/opeo-maven-plugin#348]
The puzzle `329-939b7fc0` from #329 has to be resolved: 

https://github.com/objectionary/opeo-maven-plugin/blob/c2af3985f231c712e8b53ede8b6e102a3747c6d4/src/test/java/org/eolang/opeo/SameXml.java#L84-L86

The puzzle was created by volodya-lombrozo on 12-Jul-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
@volodya-lombrozo I can take it

**Comment by volodya-lombrozo** [comment]
@h1alexbel Please, go ahead!
