### ISSUE TITLE
The `SameXml` class is a duplicate from `jeo-maven-plugin`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#352]
`jeo-maven-plugin` have the same `SameXml` [class](https://github.com/objectionary/jeo-maven-plugin/blob/master/src/test/java/org/eolang/jeo/SameXml.java) in the repository. Recently I just copied this class to `opeo-maven-plugin`. But it's better to reuse it from `jeo-maven-plugin` instead. This is possible because `opeo-maven-plugin` uses `jeo-maven-plugin` as a dependency.

**Comment by h1alexbel** [comment]
@volodya-lombrozo hm, it looks that we can't use this class since it located in `src/test` package. Am I miss something?

**Comment by h1alexbel** [comment]
@volodya-lombrozo I think we can move `SameXml` into `representation` inside main package.

**Comment by volodya-lombrozo** [comment]
@h1alexbel You are absolutely right. Agree. Let's do [it](https://github.com/objectionary/jeo-maven-plugin/issues/642).

**Comment by h1alexbel** [comment]
@volodya-lombrozo let's release new version of https://github.com/objectionary/jeo-maven-plugin and close this issue

**Comment by volodya-lombrozo** [comment]
@h1alexbel Yes, I will do it soon. I'm [updating dependencies](https://github.com/objectionary/jeo-maven-plugin/pull/649) now. When this PR will be finished, I will release a new version.
