### ISSUE TITLE
Small Inconsistencies in 'PHI' printing

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#371]
`PHI` expressions produced from `xmir` generated by `opeo-maven-plugin` contain some [mistakes](https://github.com/objectionary/normalizer/issues/379#issuecomment-2273575804). We should fix them.
Do check `PHI` expressions, you can run [normaliser](https://github.com/objectionary/normalizer).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#373](https://github.com/objectionary/opeo-maven-plugin/issues/373) is still not solved.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.3.3`, title is `Version 0.3.3`.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#373](https://github.com/objectionary/opeo-maven-plugin/issues/373) is solved here.
