### ISSUE TITLE
Refactoring: Agent Base Architecture

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#376]
We decided to modify the architecture slightly. Currently, we process instructions one by one. We search for an appropriate handler for each instruction, which is fast but not easily extendable. Right now, we have relatively high coupling between classes.

We can try implementing a different agent-based architecture. Instead of instructing handlers on which instruction to handle, we can implement a set of agents that would scan the entire instruction stack and independently decide how to decompile different parts of it.
This might make the architecture much more flexible.

In the beginning, we should create a sketch: just a few classes that would partially describe the entire solution.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#383](https://github.com/objectionary/opeo-maven-plugin/issues/383), [#384](https://github.com/objectionary/opeo-maven-plugin/issues/384) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#383](https://github.com/objectionary/opeo-maven-plugin/issues/383) is still not solved; solved: [#384](https://github.com/objectionary/opeo-maven-plugin/issues/384).
