### ISSUE TITLE
Preserve type information

### ISSUE THREAD

**Issue by deemp** [objectionary/opeo-maven-plugin#389]
@volodya-lombrozo

Currently, for stream optimizations, the `normalizer` expects exact matching of an attribute name (see https://github.com/objectionary/normalizer/issues/470#issuecomment-2288894330) because `normalizer` works with objects of particular classes.

However, `opeo-maven-plugin` doesn't provide the information about the class of the object that an attribute belongs to.

**Comment by volodya-lombrozo** [comment]
@deemp Thank you for reporting the bug. I will take a look soon.

**Comment by 0crat** [comment]
@deemp Hey there, bug hunter! 🐛 Awesome job spotting that new bug - you've just scored yourself 10 points! Your eagle eye is helping us level up our project's quality. Got any more [suspicious code](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) on your radar? [Don't hold back](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html), [let us know](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html)! Your current score is [156 points](https://www.eolang.org/zerocracy/objectionary-vitals.html) - keep it up!

**Comment by volodya-lombrozo** [comment]
We need to add prefixes with types for all the methods:
```phi
   α1 ↦ ξ.java.util.stream.j$Stream.java_util_Stream$of(
                          ....
                        ).java_util_Stream$map(
                          ....
                        ).java_util_Stream$collect(...)
```

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.3.6`, title is `Version 0.3.6`.

**Comment by volodya-lombrozo** [comment]
@deemp Could you check the current version of `opeo-maven-plugin` please? Now it adds type information to the invocations:

```
   α1 ↦ ξ.java.util.stream.j$Stream.java_util_Stream$of(
                          ....
                        ).java_util_Stream$map(
                          ....
                        ).java_util_Stream$collect(...)
```

The `0.3.6` is released.

**Comment by volodya-lombrozo** [comment]
@deemp Could you check the new `0.3.7` version, please? It should solve the problem with `[]` symbols.

**Comment by deemp** [comment]
@volodya-lombrozo, thanks for the quick fix! Yes, the new version produces the correct PHI code.

**Comment by volodya-lombrozo** [comment]
@deemp Can we close this issue then?

**Comment by deemp** [comment]
@volodya-lombrozo, yes
