### ISSUE TITLE
Add One More Agent For Tracing Agents Usage

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#393]
Sometimes it's hard to understand which agent was applied for decompilation and what result we got after using the agent.
So, we need one more [decorator](https://www.google.com/search?client=safari&rls=en&q=decorator+pattern&ie=UTF-8&oe=UTF-8) for agents that would log all agent usages. We can log:

1. instructions before
2. instructions after
3. the name of applied agent

and so on.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#400](https://github.com/objectionary/opeo-maven-plugin/issues/400) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#400](https://github.com/objectionary/opeo-maven-plugin/issues/400) is solved here.
