### ISSUE TITLE
The `help` goal is not available

### ISSUE THREAD

**Issue by yegor256** [objectionary/opeo-maven-plugin#409]
I'm running this:

```
$ mvn jeo:help
Could not find goal 'help' in plugin org.eolang:opeo-maven-plugin:0.1.10 among available goals assemble, disassemble
```

Every Maven plugin should have this goal. See how it's done in eo-maven-plugin: https://github.com/objectionary/eo/blob/master/eo-maven-plugin/pom.xml#L409

**Comment by yegor256** [comment]
@volodya-lombrozo would be great if you can fix this urgently and release a new version

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.3.4`, title is `Version 0.3.4`.

**Comment by volodya-lombrozo** [comment]
@yegor256 Done. Could you try with the new version of the plugin `0.3.4`. BTW, Rultor works extremely slow. ~ 1h to merge and release a new version.

**Comment by yegor256** [comment]
@volodya-lombrozo thanks! As for rultor, I'm looking into it.
