### ISSUE TITLE
Use  the `j$` prefix for class names during decompilation/compilation

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#420]
We need to add `j$` prefix during the decompilation for all the created objects. This is needed to avoid the problem with naming in `eo`.

> `eo` doesn't allow to use capital letters at the first place

For example, now we have such problems like [this](https://github.com/objectionary/normalizer/issues/470#issuecomment-2288796470) and [this](https://github.com/objectionary/normalizer/issues/470#issuecomment-2288840680).

**Comment by 0crat** [comment]
@volodya-lombrozo Hey there! 👋 Sorry your ticket didn't make the cut this time. As per our policy, that's a -16 point deduction. But don't sweat it! Your balance is still a healthy [+278](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep those bug reports and ideas coming – they're super valuable for improving our project. Just aim for a bit more precision next time. Remember, [bugs are welcome](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html), so don't hesitate to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) them. You're doing great!
