### ISSUE TITLE
Refactor DecompilerMachine - use AstNode in stack

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#44]
Currently we have `stack` and `root` field in the `DecompilerMachine`, but we can significantly simplify the class by using `AstNode` directly in `stack`. In this case you might need to change handlers logic a bit.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#49](https://github.com/objectionary/opeo-maven-plugin/issues/49) is still not solved.
