### ISSUE TITLE
Copy integration test for simple optimization

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#6]
In order to implement simple optimization in `jeo` plugin, we created the integration test:
https://github.com/objectionary/jeo-maven-plugin/blob/master/src/test/resources/packs/simple_objects.yaml
We need to transfer it from `jeo` repository to this repository.
The integration test was originally developed for the https://github.com/objectionary/jeo-maven-plugin/issues/102 issue

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#9](https://github.com/objectionary/opeo-maven-plugin/issues/9) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo all 2 puzzles are solved here: [#18](https://github.com/objectionary/opeo-maven-plugin/issues/18), [#9](https://github.com/objectionary/opeo-maven-plugin/issues/9).
