### ISSUE TITLE
Provide the OPEO paper

### ISSUE THREAD

**Issue by deemp** [objectionary/opeo-maven-plugin#67]
Probably related to #66

- [ ] @yegor256 provides the OPEO paper in this repo
- [ ] Include links to materials that explain
  - [ ] What's Java bytecode
  - [ ] How objects, classes, types are represented at runtime

**Comment by yegor256** [comment]
@deemp it's published: https://github.com/objectionary/opeo-maven-plugin/tree/master/paper We will update the content incrementally
