### ISSUE TITLE
Provide the jump elimination paper

### ISSUE THREAD

**Issue by Anatolay** [objectionary/opeo-maven-plugin#72]
During the meeting (https://github.com/objectionary/normalizer/issues/33) it was mentioned that in the jump elimination paper there are uses of quantifiers, and that there might be a request to support them in the normalizer.

- [ ] @yegor256 provides paper.
- [ ] Example of anticipated quantifier usage is provided

**Comment by yegor256** [comment]
@Anatolay I sent it to the Telegram chat (can't publish online, it's owned by ACM)
