### ISSUE TITLE
The simplest implementation of bytecode decompilation

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#8]
We have to implement simple transformation that would transform the following java bytecode (I printed java for simplicity):
```java
new B(new A(42)).bar();
```

into eo:
```
(B.new (A.new 42)).bar
```

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#11](https://github.com/objectionary/opeo-maven-plugin/issues/11), [#12](https://github.com/objectionary/opeo-maven-plugin/issues/12), [#13](https://github.com/objectionary/opeo-maven-plugin/issues/13) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#11](https://github.com/objectionary/opeo-maven-plugin/issues/11), [#12](https://github.com/objectionary/opeo-maven-plugin/issues/12) are still not solved; solved: [#13](https://github.com/objectionary/opeo-maven-plugin/issues/13).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#11](https://github.com/objectionary/opeo-maven-plugin/issues/11) is still not solved; solved: [#12](https://github.com/objectionary/opeo-maven-plugin/issues/12), [#13](https://github.com/objectionary/opeo-maven-plugin/issues/13).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#22](https://github.com/objectionary/opeo-maven-plugin/issues/22) is still not solved; solved: [#11](https://github.com/objectionary/opeo-maven-plugin/issues/11), [#12](https://github.com/objectionary/opeo-maven-plugin/issues/12), [#13](https://github.com/objectionary/opeo-maven-plugin/issues/13).

**Comment by 0pdd** [comment]
@volodya-lombrozo all 4 puzzles are solved here: [#11](https://github.com/objectionary/opeo-maven-plugin/issues/11), [#12](https://github.com/objectionary/opeo-maven-plugin/issues/12), [#13](https://github.com/objectionary/opeo-maven-plugin/issues/13), [#22](https://github.com/objectionary/opeo-maven-plugin/issues/22).
