### ISSUE TITLE
wrong attribute data="tuple" in the XML produced by the "decompile" goal

### ISSUE THREAD

**Issue by yegor256** [objectionary/opeo-maven-plugin#91]
Now, the `decompile` goal produces XML that contains `data="tuple"` attribute, which is not acceptable in XMIR. Instead, we should say `star=""`.

**Comment by yegor256** [comment]
@maxonfjvipon please, provide more details, if necessary

**Comment by yegor256** [comment]
@volodya-lombrozo this one is urgent, since it blocks the benchmark

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo if you check [`XeEoListener`](https://github.com/objectionary/eo/blob/878b3d512d60e9704a4c905a6077bc6f8575e701/eo-parser/src/main/java/org/eolang/parser/XeEoListener.java#L337) you may see that we add `star` attribute if EO object is `*`

EO:
```
* 1 2
```

After parsing:
```xml
<o base="tuple" star="">
  <o base="int" data="bytes">...01</o>
  <o base="int" data="bytes">...02</o>
</o>
```

Then on `optimize` step such will be converted to
```xml
<o base="org.eolang.tuple">
  <o base="org.eolang.tuple">
    <o base=".empty">
      <o base="org.eolang.tuple">
    <o base="int" data="bytes">...</o>
  <o base="int" data="bytes">...02</o>
</o>
```

Which is equivalent to the next EO:
```
```

**Comment by maxonfjvipon** [comment]
@yegor256 `PhiMojo`*

**Comment by volodya-lombrozo** [comment]
@yegor256  @maxonfjvipon Do you have an `xml` which I can just insert into `plugin` section of `pom.xml? Or maybe an example of `PhiMojo` usage?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo you may check this [test](https://github.com/objectionary/eo/blob/b91c80f904611ed6f24793f30f13cc0956ef0cbd/eo-maven-plugin/src/test/java/org/eolang/maven/PhiMojoTest.java#L65) and these [packs](https://github.com/objectionary/eo/tree/master/eo-maven-plugin/src/test/resources/org/eolang/maven/phi) for the test.

Here we parse EO code, optimize, converts to phi and save

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo sorry, I didn't get you question correctly.
You meant something like this?
```xml
<plugin>
  <groupId>org.eolang</groupId>
  <artifactId>eo-maven-plugin</artifactId>
  <version>${project.version}</version>
  <executions>
    <execution>
      <id>to-phi</id>
      <goals>
        <goal>xmir-to-phi</goal>
      </goals>
      <configuration>
        <phiInputDir>${project.build.directory}/eo/2-optimize</phiInputDir> <!-- take XMIR from here -->
        <phiOutputDir>${project.build.directory}/eo/phi</phiOutputDir> <!-- Result .phi files here -->
      </configuration>
    </execution>
  </executions>
</plugin>
```

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Yes, I've already derived it myself

**Comment by volodya-lombrozo** [comment]
@yegor256 @maxonfjvipon I've tried to run the following goal on the one of my integration tests:
```xml
<plugin>
  <groupId>org.eolang</groupId>
  <artifactId>eo-maven-plugin</artifactId>
  <version>0.34.4</version>
  <executions>
    <execution>
      <id>convert-xmir-to-phi</id>
      <phase>process-classes</phase>
      <goals>
        <goal>xmir-to-phi</goal>
      </goals>
      <configuration>
        <phiInputDir>${project.build.directory}/generated-sources/xmir</phiInputDir>
        <phiOutputDir>${project.build.directory}/generated-sources/phi</phiOutputDir>
      </configuration>
    </execution>
  </executions>
</plugin>
```

And got exception:
```
[ERROR] net.sf.saxon.style.XSLMessage@45e2d71f: Attribute @line is absent at "ALOAD-24"
```

I don't have the information about lines yet (and it would be strange if I should). Most probably it will be much easier to disable this check from your side.

**Comment by yegor256** [comment]
@volodya-lombrozo just put `line="999"`, this should be enough. Completely disabling this check would be unreasonable, since XMIR is expected to _always_ be the result of EO parsing (that's why the lines).

**Comment by yegor256** [comment]
@maxonfjvipon I believe, both `PrintMojo` and `PhiMojo` will work well as a test, since they both use the same XMIR validation mechanism, through XSD. Am I wrong?

**Comment by maxonfjvipon** [comment]
@yegor256 yes, `PhiMojo` checks validates XMIR through XSD

**Comment by volodya-lombrozo** [comment]
@yegor256 @maxonfjvipon Could you update `jee-maven-plugin` ( `jeo`, not `opeo`!) up to `0.2.17` version, please? It should help.

**Comment by yegor256** [comment]
@volodya-lombrozo this error disappeared after the update of JEO to 0.2.17, thanks!
