### ISSUE TITLE
Update eo-maven-plugin version 

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/opeo-maven-plugin#95]
We need to update `eo-maven-plugin` version up to `0.35.0`. Then we have to fix human readable print of eo according with the following issue: https://github.com/objectionary/eo/issues/2758

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#100](https://github.com/objectionary/opeo-maven-plugin/issues/100) is solved here.
